name: Backend CI

on:
  push:
    branches: [develop, main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [develop, main]
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build y validar .NET
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore backend/Hemeroteca.API/Hemeroteca.API.csproj

      - name: Compilar
        run: dotnet build backend/Hemeroteca.API/Hemeroteca.API.csproj --no-restore --configuration Release

      - name: Publicar
        run: dotnet publish backend/Hemeroteca.API/Hemeroteca.API.csproj --no-restore --configuration Release
